# Site settings
title: Luais
email: Luais@live.com
description: Um lindo tema feito para jekyll e com o <3
baseurl: "/zetsu"
url: "http://luais.github.io"

author:
  name     : 'Hongli Yang'
  email    : luais@live.com
  url      : http://luaisgithub.io
  facebook : http://facebook.com/fernando.dev
  twitter  : http://twitter.com/nandomoreirame

github: https://github.com/nandomoreirame/zetsu
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
